export const LS_KEYS = {
  selectedItems: "app:selectedItems:v2",
  customSongs: "app:customSongs:v2",
  legacyCustomSongs: "app:customSongs:v1",
  out2Bg: "app:out2Bg",
  legacyOut2SecondLang: "app:out2SecondLang",
  outputConfig: "app:outputConfig",
  netMirror: "app:netMirror",
  netEdgeFade: "app:netEdgeFade:v2",
  netBoxAlignX: "app:netBoxAlignX",
  netBoxAlignY: "app:netBoxAlignY",
  netBoxModeX: "app:netBoxModeX",
  netBoxModeY: "app:netBoxModeY",
  netBoxWidth: "app:netBoxWidth:v2",
  netBoxHeight: "app:netBoxHeight:v2",
  netBoxPadX: "app:netBoxPadX",
  netBoxPadY: "app:netBoxPadY",
  netBoxScale: "app:netBoxScale",
  netBoxRadius: "app:netBoxRadius",
  netBoxAlpha: "app:netBoxAlpha",
  netBoxOffsetX: "app:netBoxOffsetX",
  netBoxOffsetY: "app:netBoxOffsetY",
  dividerWidth: "app:dividerWidth",
  localFadeMs: "app:localFadeMs",
  streamFadeMs: "app:streamFadeMs",
  netFadeMs: "app:netFadeMs",
  localBibleScale: "app:localBibleScale",
  streamBibleScale: "app:streamBibleScale",
  localMessageScale: "app:localMessageScale",
  streamMessageScale: "app:streamMessageScale",
  localTightLabels: "app:localTightLabels",
  streamTightLabels: "app:streamTightLabels",
  visiblePreviews: "app:visiblePreviews",
  songFooter: "app:songFooter",
  translationLabels: "app:translationLabels",
  contentSelection: "app:contentSelection",
  identity: "app:identity",
  seenCatalog: "app:seenCatalog",
  searchExact: "app:searchExact",
  outputs: "app:outputs:v1",
  outputProfiles: "app:outputProfile",
  outputProfilesMigrated: "app:outputProfile:migrated",
  outputPreviewZoom: "app:outputPreviewZoom",
  layoutMain: "app:layout:main",
  layoutLeft: "app:layout:left",
} as const;

export const TRANSLATION_LABEL_PL = "Tłumaczenie";
export const TRANSLATION_LABEL_DEFAULT = "Translation";
